# Generated by Django 5.2.7 on 2025-10-14 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={
                "ordering": ["name"],
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
            },
        ),
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": ["-priority", "due_date"],
                "verbose_name": "Task",
                "verbose_name_plural": "Tasks",
            },
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(
                help_text="Unique name for this tag", max_length=50, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="category",
            field=models.CharField(
                default="general",
                help_text="Category to group related tasks (e.g., 'finance', 'health')",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="completed",
            field=models.BooleanField(
                default=False, help_text="Whether this task has been completed"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="When this task was created"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(
                blank=True, help_text="Optional detailed description of the task"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="due_date",
            field=models.DateTimeField(
                blank=True, help_text="When this task is due (optional)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.IntegerField(
                choices=[
                    (1, "Low"),
                    (2, "Medium"),
                    (3, "High"),
                    (4, "Urgent"),
                    (5, "Critical"),
                ],
                default=2,
                help_text="Task priority level",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Tags for flexible task organization",
                related_name="tasks",
                to="core.tag",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="title",
            field=models.CharField(
                help_text="Short description of what needs to be done", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="When this task was last modified"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="user",
            field=models.ForeignKey(
                help_text="The user who owns this task",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
