# Generated by Django 5.2.7 on 2025-10-16 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_tag_options_alter_task_options_alter_tag_name_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.IntegerField(blank=True, null=True)),
                ("occupation", models.CharField(blank=True, max_length=100, null=True)),
                ("is_student", models.BooleanField(default=False)),
                (
                    "filing_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("single", "Single"),
                            ("married_joint", "Married Filing Jointly"),
                            ("married_separate", "Married Filing Separately"),
                            ("head_of_household", "Head of Household"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("has_dependents", models.BooleanField(default=False)),
                ("dependent_count", models.IntegerField(default=0)),
                (
                    "typical_tax_filing_month",
                    models.IntegerField(
                        blank=True,
                        help_text="1-12, when user typically files taxes",
                        null=True,
                    ),
                ),
                ("has_hsa", models.BooleanField(default=False)),
                ("has_401k", models.BooleanField(default=False)),
                ("is_homeowner", models.BooleanField(default=False)),
                ("has_student_loans", models.BooleanField(default=False)),
                ("has_health_insurance", models.BooleanField(default=False)),
                ("insurance_renewal_month", models.IntegerField(blank=True, null=True)),
                ("recent_life_events", models.JSONField(blank=True, default=list)),
                (
                    "preferred_reminder_frequency",
                    models.CharField(
                        choices=[
                            ("weekly", "Weekly"),
                            ("biweekly", "Bi-weekly"),
                            ("monthly", "Monthly"),
                        ],
                        default="weekly",
                        max_length=20,
                    ),
                ),
                ("onboarding_completed", models.BooleanField(default=False)),
                ("profile_completeness", models.IntegerField(default=0)),
                ("last_profile_update", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
