# Generated by Django 5.2.7 on 2025-10-29 02:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=200)),
                ('apartment_unit', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=7)),
                ('country', models.CharField(default='Canada', max_length=100)),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_phone_number', models.CharField(max_length=20)),
                ('alternate_phone_number', models.CharField(blank=True, max_length=20)),
                ('email_address', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Contact Information',
                'verbose_name_plural': 'Contact Information Records',
            },
        ),
        migrations.CreateModel(
            name='LegalName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Legal Name',
                'verbose_name_plural': 'Legal Names',
            },
        ),
        migrations.CreateModel(
            name='PassportGuarantor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('canadian_passport_number', models.CharField(max_length=8)),
                ('years_known', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SupportingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('PASSPORT', 'Passport'), ('DRIVERS_LICENSE', "Driver's License"), ('BIRTH_CERT', 'Birth Certificate'), ('CITIZENSHIP', 'Citizenship Card/Certificate'), ('PR_CARD', 'Permanent Resident Card'), ('HEALTH_CARD', 'Health Card'), ('SIN_CARD', 'Social Insurance Number Card'), ('BANK_STATEMENT', 'Bank Statement'), ('UTILITY_BILL', 'Utility Bill')], max_length=50)),
                ('issuing_authority', models.CharField(max_length=200)),
                ('document_number', models.CharField(max_length=50)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('functional_role', models.CharField(choices=[('IDENTITY', 'Proof of Identity'), ('ADDRESS', 'Proof of Address'), ('STATUS', 'Proof of Status'), ('INCOME', 'Proof of Income'), ('EDUCATION', 'Proof of Education')], max_length=50)),
            ],
            options={
                'verbose_name': 'Supporting Document',
                'verbose_name_plural': 'Supporting Documents',
            },
        ),
        migrations.CreateModel(
            name='PassportReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('relationship', models.CharField(max_length=100)),
                ('is_family', models.BooleanField()),
                ('contact_information', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.contactinformation')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=200)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('X', 'X')], max_length=1)),
                ('height', models.DecimalField(decimal_places=2, help_text='Height in centimeters', max_digits=5)),
                ('gender', models.CharField(blank=True, max_length=50)),
                ('former_names', models.ManyToManyField(blank=True, related_name='former_names', to='core.legalname')),
                ('legal_name', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.legalname')),
            ],
            options={
                'verbose_name': 'Personal Information',
                'verbose_name_plural': 'Personal Information Records',
            },
        ),
        migrations.CreateModel(
            name='OSAPApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('REVIEW', 'Under Review'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dependency_information', models.JSONField()),
                ('academic_information', models.JSONField()),
                ('student_financials', models.JSONField()),
                ('parental_financials', models.JSONField(blank=True, null=True)),
                ('spousal_financials', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.personalinformation')),
            ],
            options={
                'verbose_name': 'OSAP Application',
                'verbose_name_plural': 'OSAP Applications',
            },
        ),
        migrations.CreateModel(
            name='SINApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('REVIEW', 'Under Review'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submission_method', models.CharField(choices=[('ONLINE', 'Online'), ('MAIL', 'By Mail'), ('IN_PERSON', 'In Person')], max_length=20)),
                ('application_type', models.CharField(choices=[('NEW', 'New SIN'), ('REPLACEMENT', 'Replacement'), ('UPDATE', 'Information Update'), ('CONFIRMATION', 'Confirmation of SIN')], max_length=20)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.address')),
                ('applicant_information', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.personalinformation')),
                ('contact_information', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.contactinformation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('submitted_documents', models.ManyToManyField(to='core.supportingdocument')),
            ],
            options={
                'verbose_name': 'SIN Application',
                'verbose_name_plural': 'SIN Applications',
            },
        ),
        migrations.CreateModel(
            name='PassportApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('REVIEW', 'Under Review'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('occupation_history', models.JSONField(default=list)),
                ('addresses_last_two_years', models.ManyToManyField(to='core.address')),
                ('contact_information', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.contactinformation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('guarantor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.passportguarantor')),
                ('references', models.ManyToManyField(to='core.passportreference')),
                ('applicant_information', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.personalinformation')),
                ('submitted_documents', models.ManyToManyField(to='core.supportingdocument')),
            ],
            options={
                'verbose_name': 'Passport Application',
                'verbose_name_plural': 'Passport Applications',
            },
        ),
        migrations.CreateModel(
            name='OntarioProvincialIdApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('REVIEW', 'Under Review'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application_type', models.CharField(choices=[('DRIVER_LICENSE', "Driver's License"), ('PHOTO_CARD', 'Photo Card')], max_length=20)),
                ('is_surrendering_existing_id', models.BooleanField(default=False)),
                ('medical_information', models.JSONField(blank=True, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('applicant_information', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.personalinformation')),
                ('submitted_documents', models.ManyToManyField(to='core.supportingdocument')),
            ],
            options={
                'verbose_name': 'Ontario Provincial ID Application',
                'verbose_name_plural': 'Ontario Provincial ID Applications',
            },
        ),
        migrations.CreateModel(
            name='FoundationalDocumentsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_verified', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact_information', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.contactinformation')),
                ('current_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='current_resident', to='core.address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='foundational_documents', to=settings.AUTH_USER_MODEL)),
                ('personal_information', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.personalinformation')),
                ('supporting_documents', models.ManyToManyField(blank=True, to='core.supportingdocument')),
            ],
            options={
                'verbose_name': 'Foundational Documents Snapshot',
                'verbose_name_plural': 'Foundational Documents Snapshots',
            },
        ),
    ]
