# Generated by Django 5.2.7 on 2025-11-01 21:30

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_address_contactinformation_legalname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinapplication',
            name='sin_number',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text="Applicant's SIN (encrypted at rest)", null=True),
        ),
        migrations.AlterField(
            model_name='passportguarantor',
            name='canadian_passport_number',
            field=encrypted_model_fields.fields.EncryptedCharField(help_text="Guarantor's Canadian passport number (encrypted at rest)"),
        ),
    ]
